### ISSUE TITLE
About the utils and slayerSNN 

### ISSUE THREAD

**Issue by lunaWU628** [lisiqi19971013/Event_Enhanced_DeOcc#2]
Hi, 
      wonderful work!
      But utils seems to be a package that you wrote by yourself. Could you please upload utils and slayerSNN to GitHub?
      Thanks!
![1660788200514](https://user-images.githubusercontent.com/90367095/185276099-01452eee-4445-4494-9d1b-2584c40439b9.png)
![1660788876548](https://user-images.githubusercontent.com/90367095/185278085-618af775-8622-4c2c-900b-b05f838e3f75.png)

**Comment by one00101** [comment]
同学你好，请问你知道在哪里可以找到数据集Occlusion-400吗？

**Comment by wujihua628** [comment]
不知道哦

**Comment by lunaWU628** [comment]
不知道哦。没用过这个数据集

**Comment by lisiqi19971013** [comment]
Hi, we have uploaded the utils folder. The slayerSNN could be installed following here: https://github.com/bamsumit/slayerPytorch.

**Comment by lisiqi19971013** [comment]
Hi guys,
Our dataset is available now!
